/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme.paneli.PnlDnevnaBerba;
import forme.paneli.PnlDobavljac;
import forme.paneli.PnlLogovanje;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import komunikacija.NitKlijent;
import konstante.Konstante;
import transfer.KlijentTransferObjekat;

/**
 *
 * @author Marko
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        NitKlijent.getInstance().setFrmG(this);
        NitKlijent.getInstance().start();
        spPaneli.setViewportView(new PnlLogovanje());
        PnlDnevnaBerba.flag = 1;
//        this.addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
//
//                if (PnlDnevnaBerba.flag == 1) {
//
//                    System.exit(0);
//                } else {
//                    String[] options = new String[2];
//                    options[0] = new String("DA");
//                    options[1] = new String("NE");
//                    int odgovor = JOptionPane.showOptionDialog(null, "Stavke nisu kreirane za dnevnu berbu, ako izadjete iz programa dnevna berba ce biti obrisana. Da li ste sigruni?",
//                            "Iskljuci program",
//                            0, JOptionPane.QUESTION_MESSAGE, null, options, null);
//                    if (odgovor == JOptionPane.YES_OPTION) {
//                        try {
//                            KlijentTransferObjekat kto = new KlijentTransferObjekat();
//                            kto.setOperacija(Konstante.OPERACIJA_OBRISI_DNEVNU_BERBU1);
//                            PnlDnevnaBerba.setujDnevnuBerbu();
//                            kto.setParametar(PnlDnevnaBerba.dnevnaBerba);
//                            NitKlijent.out.writeObject(kto);
//                        } catch (IOException ex) {
//                            Logger.getLogger(PnlDnevnaBerba.class.getName()).log(Level.SEVERE, null, ex);
//                        }
//                        System.exit(0);
//                    } else {
//                        setVisible(true);
//                    }
//                }
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spPaneli = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SchroomSoft");

        jMenu1.setText("Odjava");

        jMenuItem1.setText("Odjavi se");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1008, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        if (PnlDnevnaBerba.flag == 1) {
            spPaneli.setViewportView(new PnlLogovanje());

        } else {
            String[] options = new String[2];
            options[0] = new String("DA");
            options[1] = new String("NE");
            int odgovor = JOptionPane.showOptionDialog(null, "Stavke nisu kreirane za dnevnu berbu, ako izadjete iz programa dnevna berba ce biti obrisana. Da li ste sigruni?",
                    "Iskljuci program",
                    0, JOptionPane.QUESTION_MESSAGE, null, options, null);
            if (odgovor == JOptionPane.YES_OPTION) {
                try {
                    KlijentTransferObjekat kto = new KlijentTransferObjekat();
                    kto.setOperacija(Konstante.OPERACIJA_OBRISI_DNEVNU_BERBU1);
                    PnlDnevnaBerba.setujDnevnuBerbu();
                    kto.setParametar(PnlDnevnaBerba.dnevnaBerba);
                    NitKlijent.out.writeObject(kto);
                } catch (IOException ex) {
                    Logger.getLogger(PnlDnevnaBerba.class.getName()).log(Level.SEVERE, null, ex);
                }
                spPaneli.setViewportView(new PnlLogovanje());
                PnlDnevnaBerba.flag = 1;
            }
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                final FrmGlavna frame = new FrmGlavna();
                frame.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent windowEvent) {

                        if (PnlDnevnaBerba.flag == 1) {
                            System.exit(0);
                        } else {
                            String[] options = new String[2];
                            options[0] = new String("DA");
                            options[1] = new String("NE");
                            int odgovor = JOptionPane.showOptionDialog(null, "Stavke nisu kreirane za dnevnu berbu, ako izadjete iz programa dnevna berba ce biti obrisana. Da li ste sigruni?",
                                    "Iskljuci program",
                                    0, JOptionPane.QUESTION_MESSAGE, null, options, null);
                            if (odgovor == JOptionPane.YES_OPTION) {
                                try {
                                    KlijentTransferObjekat kto = new KlijentTransferObjekat();
                                    kto.setOperacija(Konstante.OPERACIJA_OBRISI_DNEVNU_BERBU1);
                                    PnlDnevnaBerba.setujDnevnuBerbu();
                                    kto.setParametar(PnlDnevnaBerba.dnevnaBerba);
                                    NitKlijent.out.writeObject(kto);
                                } catch (IOException ex) {
                                    Logger.getLogger(PnlDnevnaBerba.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                System.exit(0);
                            } else {
                                frame.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
                            }
                        }
                    }
                });
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JScrollPane spPaneli;
    // End of variables declaration//GEN-END:variables

    public void setujPanelDobavljaci() {
        spPaneli.setViewportView(new PnlDobavljac(spPaneli));
    }

}
