/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.paneli;

import domen.DnevnaBerba;
import domen.Dobavljac;
import domen.StavkaDnevneBerbe;

import forme.modeltabele.TableModelStavkaDnevneBerbe;
import java.io.IOException;
import java.sql.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import komunikacija.NitKlijent;
import konstante.Konstante;
import transfer.KlijentTransferObjekat;

/**
 *
 * @author Marko
 */
public class PnlDnevnaBerba extends javax.swing.JPanel {

    Dobavljac dobavljac;
    JScrollPane glavna;
    public static DnevnaBerba dnevnaBerba;
    public static int flag;
    public static String id;

    /**
     * Creates new form PnlDnevnaBerba
     */
    public PnlDnevnaBerba() {
        initComponents();
    }

    public PnlDnevnaBerba(Dobavljac d, JScrollPane g) {
        this();
        dobavljac = d;
        glavna = g;
        jlbClan.setText(d.getIme() + " " + d.getPrezime());
        Date da = new Date(new java.util.Date().getTime());
        jlbDanasnjiDatum.setText(da + "");

        flag = 1;
        srediTextField(false);
        popuniTabele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbClan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDnevneBerbe = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jbtnVidiDnevnuBerbu = new javax.swing.JButton();
        jbtnObrisiDnevnuBerbu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlbDanasnjiDatum = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblStavke = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jlbIDDnevneBerbe = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfTacne = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfCenaTacne = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfPrvaKlasa = new javax.swing.JTextField();
        jtfDrugaKlasa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfTrecaKlasa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtfCenaPrvaKlasa = new javax.swing.JTextField();
        jtfCenaDrugaKlasa = new javax.swing.JTextField();
        jtfCenaTrecaKlasa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtnKreirajStavku = new javax.swing.JButton();
        jbtnIzbrisiStavku = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jtfGod = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfMesec = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtfDan = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtfBraonTacne = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jtfCenaBraonTacne = new javax.swing.JTextField();
        jtfCenaBraonRimfuz = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jtfBraonRimfuz = new javax.swing.JTextField();
        jtfBukovaca = new javax.swing.JTextField();
        jtfCenaBukovaca = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel1.setText("Član:");

        jlbClan.setText("jLabel2");

        jtblDnevneBerbe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblDnevneBerbe);

        jButton3.setText("Vrati se nazad");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbtnVidiDnevnuBerbu.setText("Vidi dnevnu berbu");
        jbtnVidiDnevnuBerbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVidiDnevnuBerbuActionPerformed(evt);
            }
        });

        jbtnObrisiDnevnuBerbu.setText("Obriši");
        jbtnObrisiDnevnuBerbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiDnevnuBerbuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jlbClan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnVidiDnevnuBerbu)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnObrisiDnevnuBerbu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlbClan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jbtnVidiDnevnuBerbu)
                    .addComponent(jbtnObrisiDnevnuBerbu)))
        );

        jTabbedPane1.addTab("Dnevne berbe", jPanel1);

        jLabel2.setText("Datum:");

        jlbDanasnjiDatum.setText("jLabel3");

        jtblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblStavke);

        jLabel3.setText("ID:");

        jButton1.setText("Kreiraj Dnevnu Berbu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tacne:");

        jLabel6.setText("kg.");

        jLabel7.setText("Cena:");

        jLabel8.setText("Prva klasa:");

        jLabel9.setText("Druga klasa:");

        jtfDrugaKlasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDrugaKlasaActionPerformed(evt);
            }
        });

        jLabel10.setText("kg.");

        jLabel11.setText("kg.");

        jLabel12.setText("Treca klasa:");

        jLabel13.setText("kg.");

        jLabel14.setText("Cena:");

        jLabel15.setText("Cena:");

        jLabel16.setText("Cena:");

        jbtnKreirajStavku.setText("Kreiraj stavku");
        jbtnKreirajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jbtnKreirajStavku)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnKreirajStavku)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jbtnIzbrisiStavku.setText("Izbriši stavku");
        jbtnIzbrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzbrisiStavkuActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sačuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jLabel17.setText("God.");

        jLabel18.setText("Mesec");

        jLabel19.setText("Dan");

        jLabel20.setText("Braon tacne:");

        jLabel21.setText("kg.");

        jLabel22.setText("Cena:");

        jLabel23.setText("Cena:");

        jLabel24.setText("Cena:");

        jLabel25.setText("Braon rimfuz:");

        jLabel26.setText("Bukovaca:");

        jLabel27.setText("kg.");

        jLabel28.setText("kg.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbDanasnjiDatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfMesec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfGod, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jlbIDDnevneBerbe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtfDrugaKlasa, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(jtfPrvaKlasa, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtfTacne, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jtfTrecaKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtfCenaTacne, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(jtfCenaPrvaKlasa)
                                        .addComponent(jtfCenaDrugaKlasa))
                                    .addComponent(jtfCenaTrecaKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jtfBraonTacne, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jtfBraonRimfuz, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel27))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jtfBukovaca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel28)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfCenaBraonRimfuz, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfCenaBukovaca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfCenaBraonTacne, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnIzbrisiStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvaj)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlbDanasnjiDatum)
                    .addComponent(jLabel5)
                    .addComponent(jtfTacne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jtfCenaTacne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jtfMesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jtfDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlbIDDnevneBerbe)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPrvaKlasa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel14)
                                .addComponent(jtfCenaPrvaKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtfDrugaKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addComponent(jtfCenaDrugaKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jtfTrecaKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jtfCenaTrecaKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jtfBraonTacne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jtfCenaBraonTacne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jtfCenaBraonRimfuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jtfBraonRimfuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)
                            .addComponent(jtfBukovaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCenaBukovaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnIzbrisiStavku, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Unos nove dnevne berbe", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDrugaKlasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDrugaKlasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDrugaKlasaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            DnevnaBerba db = new DnevnaBerba();
            int dan = 0;
            int mesec = 0;
            int godina = 0;
            dan = Integer.parseInt(jtfDan.getText());
            mesec = Integer.parseInt(jtfMesec.getText());
            godina = Integer.parseInt(jtfGod.getText());
            GregorianCalendar g = new GregorianCalendar(godina, mesec - 1, dan);
            Date d = new Date(g.getTimeInMillis());
            db.setDatum(d);
            db.setDobavljac(dobavljac);
            KlijentTransferObjekat kto = new KlijentTransferObjekat();
            kto.setOperacija(Konstante.OPERACIJA_UBACI_DNEVNU_BERBU);
            kto.setParametar(db);
            NitKlijent.out.writeObject(kto);
            srediTextField(true);
            flag = 0;
        } catch (Exception e) {
            Logger.getLogger(PnlDnevnaBerba.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Greska pri unosu datuma!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnKreirajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajStavkuActionPerformed

        try {
            popuniPrazne();
            StavkaDnevneBerbe stavka = new StavkaDnevneBerbe();
            setujDnevnuBerbu();
            stavka.setDnevnaBerba(dnevnaBerba);
            stavka.setDobavljac(dobavljac);
            stavka.setTacne(Double.parseDouble(jtfTacne.getText()));
            stavka.setPrvaKlasa(Double.parseDouble(jtfPrvaKlasa.getText()));
            stavka.setDrugaKlasa(Double.parseDouble(jtfDrugaKlasa.getText()));
            stavka.setTrecaKlasa(Double.parseDouble(jtfTrecaKlasa.getText()));
            stavka.setBraonTacne(Double.parseDouble(jtfBraonTacne.getText()));
            stavka.setBraonRimfuz(Double.parseDouble(jtfBraonRimfuz.getText()));
            stavka.setBukovaca(Double.parseDouble(jtfBukovaca.getText()));
            stavka.setCenaTacne(Double.parseDouble(jtfCenaTacne.getText()));
            stavka.setCenaPrvaKlasa(Double.parseDouble(jtfCenaPrvaKlasa.getText()));
            stavka.setCenaTrecaKlasa(Double.parseDouble(jtfCenaTrecaKlasa.getText()));
            stavka.setCenaDrugaKlasa(Double.parseDouble(jtfCenaDrugaKlasa.getText()));
            stavka.setCenaBraonTacne(Double.parseDouble(jtfCenaBraonTacne.getText()));
            stavka.setCenaBraonRimfuz(Double.parseDouble(jtfCenaBraonRimfuz.getText()));
            stavka.setCenaBukovaca(Double.parseDouble(jtfCenaBukovaca.getText()));
            NitKlijent.getInstance().getPomocnaListaStavki().add(stavka);
            refreshTable();
            jtfTacne.setText("");
            jtfPrvaKlasa.setText("");
            jtfDrugaKlasa.setText("");
            jtfTrecaKlasa.setText("");
            jtfBraonTacne.setText("");
            jtfBraonRimfuz.setText("");
            jtfBukovaca.setText("");
            jtfCenaTacne.setText("");
            jtfCenaPrvaKlasa.setText("");
            jtfCenaDrugaKlasa.setText("");
            jtfCenaTrecaKlasa.setText("");
            jtfCenaBraonTacne.setText("");
            jtfCenaBraonRimfuz.setText("");
            jtfCenaBukovaca.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri unosu elemenata stavke");
            e.printStackTrace();
        }

    }//GEN-LAST:event_jbtnKreirajStavkuActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        if (NitKlijent.getInstance().getPomocnaListaStavki().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Niste uneli stavke dnevne berbe");
        } else {
            try {
                KlijentTransferObjekat kto = new KlijentTransferObjekat();
                kto.setOperacija(Konstante.OPERACIJA_SACUVAJ_STAVKE_DNEVNE_BERBE);
                List<StavkaDnevneBerbe> stavke = NitKlijent.getInstance().getPomocnaListaStavki();
                kto.setParametar(stavke);
                NitKlijent.out.writeObject(kto);
                NitKlijent.out.reset();
            } catch (IOException ex) {
                Logger.getLogger(PnlDnevnaBerba.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (flag == 1) {
            glavna.setViewportView(new PnlDobavljac(glavna));
        } else {

            String[] options = new String[2];
            options[0] = new String("DA");
            options[1] = new String("NE");
            int odgovor = JOptionPane.showOptionDialog(this, "Ako se vratite nazad, dnevna berba ce biti obrisana, posto nema stavki. Da li zelite da se vratit nazad?",
                    "Nazad na dobavljač",
                    0, JOptionPane.QUESTION_MESSAGE, null, options, null);
            if (odgovor == JOptionPane.YES_OPTION) {
                try {
                    KlijentTransferObjekat kto = new KlijentTransferObjekat();
                    kto.setOperacija(Konstante.OPERACIJA_OBRISI_DNEVNU_BERBU);
                    setujDnevnuBerbu();
                    kto.setParametar(dnevnaBerba);
                    NitKlijent.out.writeObject(kto);
                    flag = 1;
                } catch (IOException ex) {
                    Logger.getLogger(PnlDnevnaBerba.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnIzbrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzbrisiStavkuActionPerformed
        if (jtblStavke.getSelectedRowCount() == 1) {
            NitKlijent.getInstance().getPomocnaListaStavki().remove(jtblStavke.getSelectedRow());
            TableModelStavkaDnevneBerbe tb = (TableModelStavkaDnevneBerbe) jtblStavke.getModel();
            tb.fireTableDataChanged();
        } else {
            JOptionPane.showMessageDialog(this, "Niste selektovali ni jednu stavku");
        }
    }//GEN-LAST:event_jbtnIzbrisiStavkuActionPerformed

    private void jbtnVidiDnevnuBerbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVidiDnevnuBerbuActionPerformed
        if (jtblDnevneBerbe.getSelectedRowCount() == 1) {
            glavna.setViewportView(new PnlStavke(dobavljac, glavna, NitKlijent.getInstance().getDnevneBerbe().get(jtblDnevneBerbe.getSelectedRow())));
        } else {
            JOptionPane.showMessageDialog(this, "Selektovali ste vise ili niste selektovali ni jednu dnevnu berbu");
        }
    }//GEN-LAST:event_jbtnVidiDnevnuBerbuActionPerformed

    private void jbtnObrisiDnevnuBerbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiDnevnuBerbuActionPerformed

        if (jtblDnevneBerbe.getSelectedRowCount() == 1) {
            try {
                KlijentTransferObjekat kto = new KlijentTransferObjekat();
                kto.setOperacija(Konstante.OPERACIJA_OBRISI_DNEVNU_BERBU_2);
                kto.setParametar(NitKlijent.getInstance().getDnevneBerbe().get(jtblDnevneBerbe.getSelectedRow()));
                NitKlijent.out.writeObject(kto);
            } catch (IOException ex) {
                Logger.getLogger(PnlDnevnaBerba.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Izabrali ste vise ili niste izabrali ni jednu dnevnu berbu!");
        }
    }//GEN-LAST:event_jbtnObrisiDnevnuBerbuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnIzbrisiStavku;
    private javax.swing.JButton jbtnKreirajStavku;
    private javax.swing.JButton jbtnObrisiDnevnuBerbu;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JButton jbtnVidiDnevnuBerbu;
    private javax.swing.JLabel jlbClan;
    private javax.swing.JLabel jlbDanasnjiDatum;
    public static javax.swing.JLabel jlbIDDnevneBerbe;
    public static javax.swing.JTable jtblDnevneBerbe;
    public static javax.swing.JTable jtblStavke;
    private javax.swing.JTextField jtfBraonRimfuz;
    private javax.swing.JTextField jtfBraonTacne;
    private javax.swing.JTextField jtfBukovaca;
    private javax.swing.JTextField jtfCenaBraonRimfuz;
    private javax.swing.JTextField jtfCenaBraonTacne;
    private javax.swing.JTextField jtfCenaBukovaca;
    private javax.swing.JTextField jtfCenaDrugaKlasa;
    private javax.swing.JTextField jtfCenaPrvaKlasa;
    private javax.swing.JTextField jtfCenaTacne;
    private javax.swing.JTextField jtfCenaTrecaKlasa;
    private javax.swing.JTextField jtfDan;
    private javax.swing.JTextField jtfDrugaKlasa;
    private javax.swing.JTextField jtfGod;
    private javax.swing.JTextField jtfMesec;
    private javax.swing.JTextField jtfPrvaKlasa;
    private javax.swing.JTextField jtfTacne;
    private javax.swing.JTextField jtfTrecaKlasa;
    // End of variables declaration//GEN-END:variables

    private void popuniTabele() {
        try {
            jtblStavke.setModel(new TableModelStavkaDnevneBerbe(NitKlijent.getInstance().getPomocnaListaStavki()));
            KlijentTransferObjekat kto = new KlijentTransferObjekat();
            kto.setOperacija(Konstante.OPERACIJA_VRATI_LISTU_DNEVNIH_BERBI);
            kto.setParametar(dobavljac);
            NitKlijent.out.writeObject(kto);

        } catch (IOException ex) {
            Logger.getLogger(PnlDnevnaBerba.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void refreshTable() {
        TableModelStavkaDnevneBerbe tm = (TableModelStavkaDnevneBerbe) jtblStavke.getModel();
        tm.fireTableDataChanged();
    }

    public static void setujDnevnuBerbu() {
        List<DnevnaBerba> db = NitKlijent.getInstance().getDnevneBerbe();
        for (int i = 0; i < db.size(); i++) {
            if (db.get(i).getDnevnaBerbaID() == Integer.parseInt(id)) {
                dnevnaBerba = db.get(i);
            }
        }
    }

    private void srediTextField(boolean a) {
        jtfTacne.setEnabled(a);
        jtfPrvaKlasa.setEnabled(a);
        jtfDrugaKlasa.setEnabled(a);
        jtfTrecaKlasa.setEnabled(a);
        jtfBraonTacne.setEnabled(a);
        jtfBraonRimfuz.setEnabled(a);
        jtfBukovaca.setEnabled(a);
        jtfCenaTacne.setEnabled(a);
        jtfCenaPrvaKlasa.setEnabled(a);
        jtfCenaDrugaKlasa.setEnabled(a);
        jtfCenaTrecaKlasa.setEnabled(a);
        jtfCenaBraonTacne.setEnabled(a);
        jtfCenaBraonRimfuz.setEnabled(a);
        jtfCenaBukovaca.setEnabled(a);

    }

    private void popuniPrazne() {
        if (jtfTacne.getText().equals("")) {
            jtfTacne.setText(0 + "");
        }
        if (jtfCenaTacne.getText().equals("")) {
            jtfCenaTacne.setText(0 + "");
        }
        if (jtfPrvaKlasa.getText().equals("")) {
            jtfPrvaKlasa.setText(0 + "");
        }
        if (jtfCenaPrvaKlasa.getText().equals("")) {
            jtfCenaPrvaKlasa.setText(0 + "");
        }
        if (jtfDrugaKlasa.getText().equals("")) {
            jtfDrugaKlasa.setText(0 + "");
        }
        if (jtfCenaDrugaKlasa.getText().equals("")) {
            jtfCenaDrugaKlasa.setText(0 + "");
        }
        if (jtfTrecaKlasa.getText().equals("")) {
            jtfTrecaKlasa.setText(0 + "");
        }
        if (jtfCenaTrecaKlasa.getText().equals("")) {
            jtfCenaTrecaKlasa.setText(0 + "");
        }
        if (jtfBraonTacne.getText().equals("")) {
            jtfBraonTacne.setText(0 + "");
        }
        if (jtfCenaBraonTacne.getText().equals("")) {
            jtfCenaBraonTacne.setText(0 + "");
        }
        if (jtfBraonRimfuz.getText().equals("")) {
            jtfBraonRimfuz.setText(0 + "");
        }
        if (jtfCenaBraonRimfuz.getText().equals("")) {
            jtfCenaBraonRimfuz.setText(0 + "");
        }
        if (jtfBukovaca.getText().equals("")) {
            jtfBukovaca.setText(0 + "");
        }
        if (jtfCenaBukovaca.getText().equals("")) {
            jtfCenaBukovaca.setText(0 + "");
        }
    }

}
