/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.paneli;

import domen.AdministrativniRadnik;
import domen.Dobavljac;
import domen.Zaduzenje;
import java.io.IOException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import komunikacija.NitKlijent;
import konstante.Konstante;
import transfer.KlijentTransferObjekat;

/**
 *
 * @author Marko
 */
public class PnlZaduzenja extends javax.swing.JPanel {

    Dobavljac dobavljac;
    JScrollPane glavna;
    ButtonGroup bg;

    /**
     * Creates new form PnlZaduzenja
     */
    public PnlZaduzenja() {
        initComponents();
    }

    public PnlZaduzenja(Dobavljac d, JScrollPane g) {
        this();
        dobavljac = d;
        glavna = g;
        jlbClan.setText(d.getIme() + " " + d.getPrezime());
        jtfBrojVreca.setEnabled(false);
        popuniTabelu();
        srediRadioButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrbPrevoz = new javax.swing.JRadioButton();
        jrbKompost = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jtfBrojVreca = new javax.swing.JTextField();
        jbtnDodajZaduzenje = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblZaduzenja = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jlbClan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbtnVrati = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Novo zaduzenje", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jrbPrevoz.setText("Prevoz");
        jrbPrevoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPrevozActionPerformed(evt);
            }
        });

        jrbKompost.setText("Kompost");
        jrbKompost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbKompostActionPerformed(evt);
            }
        });

        jLabel2.setText("Broj vreća:");

        jbtnDodajZaduzenje.setText("Dodaj zaduženje");
        jbtnDodajZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajZaduzenjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbPrevoz)
                .addGap(79, 79, 79)
                .addComponent(jrbKompost)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jtfBrojVreca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jbtnDodajZaduzenje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbPrevoz)
                    .addComponent(jrbKompost)
                    .addComponent(jLabel2)
                    .addComponent(jtfBrojVreca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDodajZaduzenje))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sva zaduzenja", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jtblZaduzenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblZaduzenja);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        );

        jLabel1.setText("Član:");

        jlbClan.setText("jLabel2");

        jButton1.setText("Razduži");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnVrati.setText("Vrati se nazad");
        jbtnVrati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVratiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jlbClan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnVrati)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlbClan))
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jbtnVrati))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajZaduzenjeActionPerformed
        Zaduzenje z = new Zaduzenje();
        z.setDobavljac(dobavljac);
        Date d = new Date(new java.util.Date().getTime());
        z.setDatumZaduzenja(d);
        z.setZaduzio(NitKlijent.getInstance().getUlogovani());
        z.setDatumRazduzenja(null);

        if (jrbPrevoz.isSelected()) {
            try {
                z.setPrevoz(true);
                KlijentTransferObjekat kto = new KlijentTransferObjekat();
                kto.setOperacija(Konstante.OPERACIJA_UNOS_ZADUZENJA);
                kto.setParametar(z);
                NitKlijent.out.writeObject(kto);
            } catch (IOException ex) {
                Logger.getLogger(PnlZaduzenja.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jrbKompost.isSelected()) {
            try {
                z.setKompost(true);
                z.setBrojVreca(Integer.parseInt(jtfBrojVreca.getText()));
                KlijentTransferObjekat kto = new KlijentTransferObjekat();
                kto.setOperacija(Konstante.OPERACIJA_UNOS_ZADUZENJA);
                kto.setParametar(z);
                NitKlijent.out.writeObject(kto);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Niste uneli ispravno broj vreca");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Niste selektovali nista!");
        }
    }//GEN-LAST:event_jbtnDodajZaduzenjeActionPerformed

    private void jrbKompostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbKompostActionPerformed
        jtfBrojVreca.setEnabled(true);
    }//GEN-LAST:event_jrbKompostActionPerformed

    private void jrbPrevozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPrevozActionPerformed
        jtfBrojVreca.setText("");
        jtfBrojVreca.setEnabled(false);
    }//GEN-LAST:event_jrbPrevozActionPerformed

    private void jbtnVratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVratiActionPerformed
        glavna.setViewportView(new PnlDobavljac(glavna));
    }//GEN-LAST:event_jbtnVratiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jtblZaduzenja.getSelectedRowCount() == 1) {
            try {
                Zaduzenje zaduzenje = NitKlijent.getInstance().getZaduzenjaZaDobavljaca().get(jtblZaduzenja.getSelectedRow());
                if (zaduzenje.getRazduzio().getIme() == null) {
                    zaduzenje.setRazduzio(NitKlijent.getInstance().getUlogovani());
                    Date d = new Date(new java.util.Date().getTime());
                    zaduzenje.setDatumRazduzenja(d);
                    KlijentTransferObjekat kto = new KlijentTransferObjekat();
                    kto.setOperacija(Konstante.OPERACIJA_IZMENI_ZADUZENJA);
                    kto.setParametar(zaduzenje);
                    NitKlijent.out.writeObject(kto);
                } else {
                    JOptionPane.showMessageDialog(this, "Vec je razduzeno");
                }
            } catch (IOException ex) {
                Logger.getLogger(PnlZaduzenja.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selektovali sve vise ili nise selektovali ni jedan red");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajZaduzenje;
    private javax.swing.JButton jbtnVrati;
    private javax.swing.JLabel jlbClan;
    private javax.swing.JRadioButton jrbKompost;
    private javax.swing.JRadioButton jrbPrevoz;
    public static javax.swing.JTable jtblZaduzenja;
    private javax.swing.JTextField jtfBrojVreca;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        try {
            KlijentTransferObjekat kto = new KlijentTransferObjekat();
            kto.setOperacija(Konstante.OPERACIJA_VRATI_ZADUZENJA);
            kto.setParametar(dobavljac);
            NitKlijent.out.writeObject(kto);
        } catch (IOException ex) {
            Logger.getLogger(PnlZaduzenja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void srediRadioButton() {
        bg = new ButtonGroup();
        bg.add(jrbPrevoz);
        bg.add(jrbKompost);
    }
}
